import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Header } from "../components/Header"
import { Links } from "@/components/Links";
import { Headline } from "@/components/Headline";

const inter = Inter({ subsets: ["latin"] });


export default function Home() {
  return (
    <>

      <Head>
        <title>Index page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <h1>Hello Next</h1>
        <Headline code={<code className={styles.code}>pages/index.js</code>}>Test</Headline> 
        <div className={styles.description}>
          <Links />
        </div>
      </main>
    </>
  );
}
